run_mode: debug                  # 开发模式, debug, release, test
addr: :8080                     # HTTP绑定端口
name: snake             # API Server的名字
url: http://127.0.0.1:8080      # pingServer函数请求的API服务器的ip:port
max_ping_count: 10              # pingServer函数try的次数
jwt_secret: Rtg9BPKNE62mB4mgvK9NGPZvQSaJWNxijxR42qRgq0iBv5
jwt_duration: 2                 # token 有效时长，单位小时
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: file,stdout            # 有2个可选项：file,stdout, 可以两者同时选择输出位置，有2个可选项：file,stdout。选择file会将日志记录到logger_file指定的日志文件中，选择stdout会将日志输出到标准输出，当然也可以两者同时选择
  logger_level: DEBUG             # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  logger_file: log/snake.log   # 日志文件
  logger_warn_file: log/snake.wf.log
  logger_error_file: log/snake.err.log
  log_format_text: true           # 日志的输出格式，json或者plaintext，true会输出成plaintext格式，false会输出成json格式
  rollingPolicy: daily            # rotate依据，可选的有：daily, size。如果选daily则根据天进行转存，如果是size则根据大小进行转存
  log_rotate_date: 1              # rotate转存时间，配合rollingPolicy: daily使用
  log_rotate_size: 1              # rotate转存大小，配合rollingPolicy: size使用
  log_backup_count: 7             # 当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
gorm:
  show_log: true                  # 是否打印SQL日志
  max_idle_conn: 10               # 最大打开的连接数
  max_open_conn: 60               # 最大的闲置的连接数
  conn_max_life_time: 60          # 连接重用的最大时间，单位分钟
db:
  name: snake
  addr: 127.0.0.1:3306
  username: root
  password: 123456
docker_db:
  name: snake
  addr: 127.0.0.1:3306
  username: root
  password: 123456
redis:
  addr: localhost:6379
  password:  # no password set
  db: 0 # use default DB
  dial_timeout: 60   # 单位：秒
  read_timeout: 2   # 单位：秒
  write_timeout: 2  # 单位：秒
  pool_size: 60
qiniu:
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
  signature_id: signature_id  # 短信签名id
  template_id: template_id    # 模板id
eth:
  url: http://127.0.0.1:7545
  #userpassphrase: 123456
  #userkeystore: {address: 6b2c4afb561241ce775ad8995535273fd4ec4c61,crypto:{cipher: aes-128-ctr,ciphertext: e493bd8892ee5a9690dc831587800d7ddb555cc1b5eb3ea88feb6b1b506e01d4,cipherparams:{iv: b90bc53121993ce513d0ceb10b947d4a},kdf: scrypt,kdfparams:{dklen: 32,n: 262144,p: 1,r: 8,salt: ea9ef88ce0ca3c39c78919b19d474630230e0b6554c4e888c2e1b6b2ead10552},mac: eac82af91106ef0ad81f528fab3c8ee1974c039798abe9b6be1eb1d49d6ca386},id: f014dea7-4fdd-4a8d-b537-c968f3ae2ee6,version: 3}
  privatekey: c2383178616a9dfddd51d56fba9a7e98f05097d710414670532f10d56e7f744c
  address: 0x6B0f066eC74f89d32f5A9937CFB9457E64359Ae7
  coin: {name: gbcom, symbol: gc, initialsupply: 100000000000000000000000000, decimals: 18}
